import { useState, useEffect } from "react";
import { useParams, useLocation, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { ArrowLeft, Download, Activity } from "lucide-react";
import { Procedure } from "@/pages/Index";
import jsPDF from "jspdf";

const ReportEditor = () => {
  const { id } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const procedure = location.state?.procedure as Procedure;

  const [reportContent, setReportContent] = useState("");

  useEffect(() => {
    if (procedure) {
      const initialReport = `EndoDoc Medical Center

COLONOSCOPY PROCEDURE REPORT

PATIENT INFORMATION                    PROCEDURE DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Patient Name: ${procedure.patientName}         Date/Time: ${new Date(procedure.date).toLocaleDateString()}
Patient ID: ${procedure.patientId}                    Physician: ${procedure.surgeon}
Date: ${new Date(procedure.date).toLocaleDateString()}             Duration: ${procedure.duration}
                                            Anesthesia: ${procedure.anesthesia}


A. PROCEDURE INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Procedure Performed: ${procedure.procedureType}


PROCEDURE TECHNIQUE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Patient's medications, allergies, past medical, surgical, social and family 
histories were reviewed and updated as appropriate. A discussion of informed 
consent was had with the patient and/or the patient's family prior to the 
procedure, including sedation. The alternatives, benefits and risks of the 
procedure including but not limited to perforation, hemorrhage, infection, 
adverse drug reaction and aspiration were discussed.


DESCRIPTION OF PROCEDURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

After discussion of informed consent, and appropriate level of sedation were 
attained, the patient was placed in the left lateral position. The patient 
was monitored continuously throughout the procedure.


FINDINGS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${procedure.findings}


DIAGNOSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Based on examination findings documented above.


RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Follow-up as clinically indicated
2. Resume normal diet
3. Contact physician if any complications arise


COMPLICATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${procedure.complications || "None"}


LIMITATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

No limitations


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated by EndoDoc Medical Documentation System
`;
      
      setReportContent(initialReport);
    }
  }, [procedure]);

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const lines = doc.splitTextToSize(reportContent, 180);
    doc.setFontSize(12);
    doc.text(lines, 15, 15);
    doc.save(`${procedure.patientId}_report.pdf`);
  };

  if (!procedure) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Card className="p-6">
          <p className="text-muted-foreground mb-4">No procedure data found</p>
          <Button onClick={() => navigate("/")} className="mt-4">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Dashboard
          </Button>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
      <header className="border-b border-border/50 bg-card/95 backdrop-blur-sm shadow-sm sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={() => navigate("/")} className="hover:bg-primary/10">
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center">
                <Activity className="w-6 h-6 text-primary-foreground" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-foreground">Medical Report Editor</h1>
                <p className="text-sm text-muted-foreground">{procedure.patientName} - {procedure.patientId}</p>
              </div>
            </div>
          </div>
          <Button onClick={handleDownloadPDF} className="gap-2 shadow-sm">
            <Download className="w-4 h-4" />
            Download PDF
          </Button>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-5xl">
        <Card className="shadow-2xl border-border/50 overflow-hidden">
          <div className="bg-gradient-to-r from-primary/10 via-accent/10 to-primary/10 p-6 border-b border-border/50">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-bold text-foreground mb-1">Procedure Report</h2>
                <p className="text-sm text-muted-foreground">Edit the report content below. All changes are saved locally.</p>
              </div>
              <div className="text-right">
                <p className="text-sm font-medium text-muted-foreground">Report ID</p>
                <p className="text-lg font-bold text-primary">{procedure.patientId}</p>
              </div>
            </div>
          </div>
          
          <div className="p-8 bg-card">
            <div className="bg-background rounded-lg border border-border shadow-inner p-6">
              <Textarea
                value={reportContent}
                onChange={(e) => setReportContent(e.target.value)}
                className="min-h-[700px] font-mono text-sm leading-relaxed resize-none border-0 focus-visible:ring-0 bg-transparent"
                placeholder="Edit the report content here..."
              />
            </div>
          </div>

          {procedure.images && procedure.images.length > 0 && (
            <div className="p-6 border-t border-border/50 bg-muted/30">
              <h3 className="text-sm font-semibold text-foreground mb-3">Procedure Images</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                {procedure.images.map((image, index) => (
                  <img 
                    key={index} 
                    src={image} 
                    alt={`Procedure image ${index + 1}`}
                    className="w-full h-24 object-cover rounded-md border border-border shadow-sm hover:shadow-md transition-shadow"
                  />
                ))}
              </div>
            </div>
          )}
        </Card>
      </main>
    </div>
  );
};

export default ReportEditor;
